# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bd',
            old_name='Numérotéléphone',
            new_name='Numerotelephone',
        ),
        migrations.RenameField(
            model_name='bd',
            old_name='Prénom',
            new_name='Prenom',
        ),
    ]
